apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgresql
  namespace: postgres
spec:
  interval: 1h
  url: https://cloudnative-pg.io/charts
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  namespace: postgres
type: Opaque
stringData:
  postgres-password: "changeme123"
  password: "changeme456"
  replication-password: "replication123"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgres
spec:
  interval: 30m
  targetNamespace: postgres
  chart:
    spec:
      chart: cloudnative-pg
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: postgresql
        namespace: postgres
      interval: 12h
  values:
    crds:
      create: true