apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgresql
  namespace: postgres
spec:
  interval: 1h
  url: https://charts.postgresql.io
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  namespace: postgres
type: Opaque
stringData:
  postgres-password: "changeme123"
  password: "changeme456"
  replication-password: "replication123"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgres
spec:
  interval: 30m
  targetNamespace: postgres
  chart:
    spec:
      chart: postgresql
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: postgresql
        namespace: postgres
      interval: 12h
  values:
    global:
      postgresql:
        username: appuser
        password: "changeme456"
        database: myapp
    
    postgresql:
      initdb:
        username: postgres
        password: "changeme123"
    
    service:
      type: LoadBalancer
    
    persistence:
      enabled: true
      storageClass: "nfs-client"
      size: 8Gi
    
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"