apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: postgres
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  namespace: postgres
type: Opaque
stringData:
  postgres-password: "changeme123"
  password: "changeme456"
  replication-password: "replication123"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgres
spec:
  interval: 30m
  targetNamespace: postgres
  chart:
    spec:
      chart: postgresql
      version: '16.2.1'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: postgres
      interval: 12h
  values:
    auth:
      enablePostgresUser: true
      existingSecret: "postgresql-secrets"
      secretKeys:
        adminPasswordKey: "postgres-password"
        userPasswordKey: "password"
        replicationPasswordKey: "replication-password"
      username: "appuser"
      database: "myapp"
    
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: "16-debian-12"
    
    primary:
      service:
        type: LoadBalancer
      
      persistence:
        enabled: true
        storageClass: "nfs-client"
        accessModes:
          - ReadWriteOnce
        size: 8Gi
      
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
    
    metrics:
      enabled: false