# 10     external-dns.alpha.kubernetes.io/target: 71.191.237.229
#
#
#
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: dummy-external-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: minio.ellin.net
spec:
  type: ExternalName
  externalName: 192.168.1.215
---
apiVersion: v1
kind: Service
metadata:
  name: s3-external-service
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: s3.ellin.net
spec:
  type: ExternalName
  externalName: 192.168.1.215
---
apiVersion: v1
kind: Service
metadata:
  name: devhost-external-service
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dev.ellin.net
spec:
  type: ExternalName
  externalName: 192.168.1.218
