apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: keycloak
spec:
  interval: 12h
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: keycloak
type: Opaque
stringData:
  admin-password: "changeme123"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 30m
  targetNamespace: keycloak
  chart:
    spec:
      chart: keycloak
      version: '24.0.5'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: keycloak
      interval: 12h
  values:
    auth:
      adminUser: admin
      existingSecret: "keycloak-secrets"
      passwordSecretKey: "admin-password"

    service:
      type: ClusterIP
      ports:
        http: 80

    ingress:
      enabled: true
      ingressClassName: "contour"
      hostname: keycloak.ellin.net
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls: true
      extraTls:
        - hosts:
            - keycloak.ellin.net
          secretName: keycloak-tls

    proxy:
      enabled: true
      mode: edge

    cache:
      enabled: true
      stackName: kubernetes
      stackFile: ""

    persistence:
      enabled: false

    postgresql:
      enabled: true
      auth:
        username: "keycloak"
        password: "keycloak123"
        database: "keycloak"
      primary:
        persistence:
          enabled: true
          storageClass: "nfs-client"
          accessModes:
            - ReadWriteOnce
          size: 8Gi

    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
